version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://auth:authpass@db:5432/authdb
      JWT_SECRET: supersecret
      PORT: 3000
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:prod"]

volumes:
  db_data: